//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WidWin
{
    using System;
    using System.Collections.Generic;
    
    public partial class videpProducerVideo
    {
        public int VideoID { get; set; }
        public byte[] VideoTitlePhoto { get; set; }
        public byte[] VideoURL { get; set; }
        public int VideoProducerNO { get; set; }
        public System.DateTime VideoDateTime { get; set; }
        public string VideoTitle { get; set; }
        public string VideoDescription { get; set; }
    
        public virtual videpUser videpUser { get; set; }
    }
}
