//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WidWin
{
    using System;
    using System.Collections.Generic;
    
    public partial class videpUser
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public videpUser()
        {
            this.videpProducerVideos = new HashSet<videpProducerVideo>();
        }
    
        public string UserFirstName { get; set; }
        public string UserLastName { get; set; }
        public string UserUserName { get; set; }
        public string UserEmail { get; set; }
        public string UserPassword { get; set; }
        public string UserTCNO { get; set; }
        public int UserID { get; set; }
        public string UserFaculty { get; set; }
        public string UserUniversity { get; set; }
        public string UserBirthday { get; set; }
        public string UserMemberType { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<videpProducerVideo> videpProducerVideos { get; set; }
    }
}
