//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WidWin
{
    using System;
    using System.Collections.Generic;
    
    public partial class vProducerVideoUser
    {
        public string UserFirstName { get; set; }
        public string UserLastName { get; set; }
        public string UserUserName { get; set; }
        public string UserEmail { get; set; }
        public string UserPassword { get; set; }
        public string UserTCNO { get; set; }
        public int UserID { get; set; }
        public string UserFaculty { get; set; }
        public string UserUniversity { get; set; }
        public Nullable<System.DateTime> UserBirthday { get; set; }
        public string UserMemberType { get; set; }
        public int VideoID { get; set; }
        public byte[] VideoTitlePhoto { get; set; }
        public byte[] VideoURL { get; set; }
        public int VideoProducerNO { get; set; }
        public System.DateTime VideoDateTime { get; set; }
        public string VideoTitle { get; set; }
        public string VideoDescription { get; set; }
    }
}
